general.import = ["~/.config/alacritty/tokyonight.toml"]
[window]
decorations = "Buttonless"
decorations_theme_variant = "Dark"
opacity = 0.9
[font]
# normal = { family = "DepartureMono Nerd Font" }
normal = { family = "CozetteVector Nerd Font" }
bold = { family = "CozetteVectorBold" }
# normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
# bold = { family = "FiraMono Nerd Font Mono", style = "Bold" }
# italic = { family = "FiraMono Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "FiraMono Nerd Font Mono", style = "Bold Italic" }
size = 16
offset = { x = 1, y = 2 }
[colors]
transparent_background_colors = true
