format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "fg:#bb9af7"
format = "[ $path ]($style)"
truncation_length = 3

[directory.substitutions]
"Documents" = "ğŸ–« "
"Downloads" = "ğŸ¢³"
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï„¦"
style = "fg:#ff9e64"
format = '[$symbol $branch ]($style)'

[git_status]
style = "fg:#9ece6a"
format = '[($all_status$ahead_behind )]($style)'

